module.exports = {
  DefaultIndex: "Work",
  DefaultKey: "title",
  DefaultAttributes: [
    "title",
    "accession_number",
    "alternate_title",
    "api_model",
    "catalog_key",
    "collection",
    "contributor",
    "create_date",
    "creator",
    "date_created",
    "description",
    "genre",
    "identifier_descriptive",
    "keywords",
    "language",
    "library_unit",
    "location",
    "physical_description_material",
    "physical_description_size",
    "preservation_level",
    "published",
    "related_material",
    "related_url",
    "rights_holder",
    "rights_statement",
    "scope_and_contents",
    "series",
    "source",
    "status",
    "style_period",
    "subject",
    "table_of_contents",
    "technique",
    "visibility",
    "work_type",
  ],
};
