AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  dc-api-v2

  Sample SAM Template for dc-api-v2

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  ElasticsearchEndpoint:
    Type: String
    Description: Elasticsearch url
  EnvironmentPrefix:
    Type: String
    Description: Index Prefix
    Default: ""
Resources:
  helloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/hello.helloHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Description: Says hello.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
  getWorkByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-work-by-id.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Gets a work by id.
      Policies:
        Version: 2012-10-17
        Statement:
          - Sid: ESHTTPPolicy
            Effect: Allow
            Action:
              - es:ESHttp*
            Resource: "*"
      Environment:
        Variables:
          ENV_PREFIX: !Ref EnvironmentPrefix
          ELASTICSEARCH_ENDPOINT: !Ref ElasticsearchEndpoint
      Events:
        Api:
          Type: Api
          Properties:
            Path: /works/{id}
            Method: GET
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
