AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  dc-api-v2

  Sample SAM Template for dc-api-v2

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  ApiSecret:
    Type: String
    Description: Secret Key for Encrypting JWTs (must match IIIF server)
  CustomDomainCertificateArn:
    Type: String
    Description: SSL Certificate for the Custom Domain Name
  CustomDomainZone:
    Type: String
    Description: Hosted Zone Name for Custom Domain
  CustomDomainHost:
    Type: String
    Description: Hostname within ApiDomainName for Custom Domain
  DcApiEndpoint:
    Type: String
    Description: URL for DC API
  DcUrl:
    Type: String
    Description: URL of Digital Collections website
  ElasticsearchEndpoint:
    Type: String
    Description: Elasticsearch url
  EnvironmentPrefix:
    Type: String
    Description: Index Prefix
    Default: ""
  NussoApiKey:
    Type: String
    Description: API key for auth server
  NussoBaseUrl:
    Type: String
    Description: Auth server URL
  V1ApiId:
    Type: String
    Description: ID of the v1 API to mount on /api/v1
  V1ApiStage:
    Type: String
    Description: Stage name of the v1 API to mount on /api/v1
    Default: latest
Resources:
  # V2 API
  getAuthCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handlers/get-auth-callback.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: NUSSO callback function.
      Environment:
        Variables:
          API_TOKEN_SECRET: !Ref ApiSecret
          DC_API_ENDPOINT: !Ref DcApiEndpoint
          DC_URL: !Ref DcUrl
          NUSSO_API_KEY: !Ref NussoApiKey
          NUSSO_BASE_URL: !Ref NussoBaseUrl
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /auth/callback
            Method: GET
  getAuthLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handlers/get-auth-login.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Performs NUSSO login.
      Environment:
        Variables:
          DC_API_ENDPOINT: !Ref DcApiEndpoint
          DC_URL: !Ref DcUrl
          NUSSO_API_KEY: !Ref NussoApiKey
          NUSSO_BASE_URL: !Ref NussoBaseUrl
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /auth/login
            Method: GET
  getAuthWhoAmIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handlers/get-auth-whoami.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Exchanges valid JWT token for user information.
      Environment:
        Variables:
          API_TOKEN_SECRET: !Ref ApiTokenSecret
          DC_API_ENDPOINT: !Ref DcApiEndpoint
          DC_URL: !Ref DcUrl
          NUSSO_API_KEY: !Ref NussoApiKey
          NUSSO_BASE_URL: !Ref NussoBaseUrl
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /auth/whoami
            Method: GET
  getCollectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handlers/get-collections.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Gets Collections.
      Policies:
        Version: 2012-10-17
        Statement:
          - Sid: ESHTTPPolicy
            Effect: Allow
            Action:
              - es:ESHttp*
            Resource: "*"
      Environment:
        Variables:
          DC_URL: !Ref DcUrl
          ENV_PREFIX: !Ref EnvironmentPrefix
          ELASTICSEARCH_ENDPOINT: !Ref ElasticsearchEndpoint
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /collections
            Method: GET
  getCollectionByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handlers/get-collection-by-id.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Gets a Collection by id.
      Policies:
        Version: 2012-10-17
        Statement:
          - Sid: ESHTTPPolicy
            Effect: Allow
            Action:
              - es:ESHttp*
            Resource: "*"
      Environment:
        Variables:
          DC_URL: !Ref DcUrl
          ENV_PREFIX: !Ref EnvironmentPrefix
          ELASTICSEARCH_ENDPOINT: !Ref ElasticsearchEndpoint
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /collections/{id}
            Method: GET
  getFileSetByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handlers/get-file-set-by-id.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Gets a FileSet by id.
      Policies:
        Version: 2012-10-17
        Statement:
          - Sid: ESHTTPPolicy
            Effect: Allow
            Action:
              - es:ESHttp*
            Resource: "*"
      Environment:
        Variables:
          DC_URL: !Ref DcUrl
          ENV_PREFIX: !Ref EnvironmentPrefix
          ELASTICSEARCH_ENDPOINT: !Ref ElasticsearchEndpoint
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /file-sets/{id}
            Method: GET
  getWorkByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handlers/get-work-by-id.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Gets a Work by id.
      Policies:
        Version: 2012-10-17
        Statement:
          - Sid: ESHTTPPolicy
            Effect: Allow
            Action:
              - es:ESHttp*
            Resource: "*"
      Environment:
        Variables:
          DC_URL: !Ref DcUrl
          ENV_PREFIX: !Ref EnvironmentPrefix
          ELASTICSEARCH_ENDPOINT: !Ref ElasticsearchEndpoint
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /works/{id}
            Method: GET
  getThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handlers/get-thumbnail.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Gets a Work's representative thumbnail.
      Policies:
        Version: 2012-10-17
        Statement:
          - Sid: ESHTTPPolicy
            Effect: Allow
            Action:
              - es:ESHttp*
            Resource: "*"
      Environment:
        Variables:
          API_TOKEN_SECRET: !Ref ApiSecret
          ENV_PREFIX: !Ref EnvironmentPrefix
          ELASTICSEARCH_ENDPOINT: !Ref ElasticsearchEndpoint
      Events:
        CollectionApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /collections/{id}/thumbnail
            Method: GET
        WorkApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /works/{id}/thumbnail
            Method: GET
  searchPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handlers/search.postSearch
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Handles OpenSearch search requests, Works only by default.
      Policies:
        Version: 2012-10-17
        Statement:
          - Sid: ESHTTPPolicy
            Effect: Allow
            Action:
              - es:ESHttp*
            Resource: "*"
      Environment:
        Variables:
          ENV_PREFIX: !Ref EnvironmentPrefix
          ELASTICSEARCH_ENDPOINT: !Ref ElasticsearchEndpoint
      Events:
        SearchApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /search
            Method: POST
        SearchWithModelsApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /search/{models}
            Method: POST
  searchGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: handlers/search.getSearch
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Handles paging requests
      Policies:
        Version: 2012-10-17
        Statement:
          - Sid: ESHTTPPolicy
            Effect: Allow
            Action:
              - es:ESHttp*
            Resource: "*"
      Environment:
        Variables:
          DC_URL: !Ref DcUrl
          ENV_PREFIX: !Ref EnvironmentPrefix
          ELASTICSEARCH_ENDPOINT: !Ref ElasticsearchEndpoint
      Events:
        SearchApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref dcApi
            Path: /search
            Method: GET
  dcApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        MaxAge: 600
      StageName: v2
      StageVariables:
        basePath: api/v2
      Domain:
        DomainName: !Sub "${CustomDomainHost}.${CustomDomainZone}"
        BasePath: api/v2
        CertificateArn: !Ref CustomDomainCertificateArn
        Route53:
          HostedZoneName: !Sub "${CustomDomainZone}."

  # v1 API Mapping
  v1Mapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiMappingKey: api/v1
      DomainName: !Sub "${CustomDomainHost}.${CustomDomainZone}"
      ApiId: !Ref V1ApiId
      Stage: !Ref V1ApiStage

  # root API
  rootApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: latest
  rootRedirect:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./redirect
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 1
      Description: Redirects to latest version of docs
      Environment:
        Variables:
          REDIRECT_TO: /docs/v2/index.html
      Events:
        RedirectApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref rootApi
            Path: /
            Method: GET

  # Documentation
  docsMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !Sub "${CustomDomainHost}.${CustomDomainZone}"
      ApiId: !Ref rootApi
      Stage: !Ref rootApilatestStage
  docsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "dcapi-docs.${CustomDomainZone}"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  docsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${docsBucket}/*"
      Bucket: !Ref docsBucket
  docsIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref rootApi
      IntegrationMethod: GET
      IntegrationType: HTTP_PROXY
      IntegrationUri: !Sub "http://${docsBucket}.s3-website-us-east-1.amazonaws.com/{proxy}"
      PayloadFormatVersion: "1.0"
  docsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref rootApi
      AuthorizationType: NONE
      RouteKey: GET /docs/v2/{proxy+}
      Target: !Sub "integrations/${docsIntegration}"
