# Build and Deploy Template for DC API
#
# Note: Any comment starting with `#*` will be removed
# at build time. This allows us to run without the
# dependency layer in development without removing the
# layer from the build.

AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::LanguageExtensions
Description: dc-api-v2 AV Download Support
Parameters:
  MediaConvertDestinationBucket:
    Type: String
    Description: S3 bucket destination for transcoded AV resource
  MediaConvertEndpoint:
    Type: String
    Description: MediaConvert endpoint
  MediaConvertJobQueueArn:
    Type: String
    Description: Job Queue ARN for MediaConvert
  MediaConvertRoleArn:
    Type: String
    Description: MediaConvert role ARN
  PyramidBucket:
    Type: String
    Description: Meadow Pyramid Bucket
  RepositoryEmail:
    Type: String
    Description: Verified email address to use as sender
  SecretsPath:
    Type: String
    Description: Prefix to use when loading configs from Secrets Manager
  SecretsPolicy:
    Type: String
    Description: IAM Policy for reading secrets
  StreamingBucket:
    Type: String
    Description: Meadow Streaming Bucket
Resources:
  apiConfiguration:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${SecretsPath}/config/av-download"
      SecretString:
        Fn::ToJsonString:
          step_function_endpoint: !Ref AWS::NoValue
          av_download_state_machine_arn: !Ref avDownloadStateMachine
          av_download_email_template: !Ref avDownloadEmailTemplate
          use_proxied_ip: true
          streaming_bucket: !Ref StreamingBucket
          media_convert_destination_bucket: !Ref MediaConvertDestinationBucket
          media_convert_endpoint: !Ref MediaConvertEndpoint
          media_convert_job_queue_arn: !Ref MediaConvertJobQueueArn
          media_convert_role_arn: !Ref MediaConvertRoleArn
          pyramid_bucket: !Ref PyramidBucket
          repository_email: !Ref RepositoryEmail
          start_audio_transcode_function: !GetAtt startAudioTranscodeFunction.Arn
          start_transcode_function: !GetAtt startTranscodeFunction.Arn
          transcode_status_function: !GetAtt transcodeStatusFunction.Arn
          get_download_link_function: !GetAtt getDownloadLinkFunction.Arn
          send_templated_email_function: !GetAtt sendTemplatedEmailFunction.Arn
  avDownloadStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        Comment: HLS stiching and save as file in s3 and email download link
        StartAt: audioOrVideo
        States:
          audioOrVideo:
            Type: Choice
            Choices:
            - Variable: "$.transcodeInput.type"
              StringEquals: audio
              Next: startAudioTranscode
            Default: startTranscode
          startAudioTranscode:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              Payload.$: "$.transcodeInput"
              FunctionName.$: "$.configuration.startAudioTranscodeFunction"
            Next: getDownloadLink
            InputPath: "$"
            ResultPath: "$.audioTranscodeOutput"
          startTranscode:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              Payload.$: "$.transcodeInput"
              FunctionName.$: "$.configuration.startTranscodeFunction"
            Next: transcodeStatus
            InputPath: "$"
            ResultPath: "$.transcodeOutput"
          transcodeStatus:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              Payload.$: "$.transcodeOutput.Payload"
              FunctionName.$: "$.configuration.transcodeStatusFunction"
            InputPath: "$"
            ResultPath: "$.transcodeOutput"
            Next: transcodeCompleted?
          transcodeCompleted?:
            Type: Choice
            Choices:
            - Variable: "$.transcodeOutput.Payload.status"
              StringEquals: COMPLETE
              Next: getDownloadLink
            - Variable: "$.transcodeOutput.Payload.status"
              StringEquals: ERROR
              Next: failWorkflow
            - Variable: "$.transcodeOutput.Payload.status"
              StringEquals: CANCELED
              Next: failWorkflow
            Default: Wait 10 seconds
          Wait 10 seconds:
            Type: Wait
            Seconds: 10
            Next: transcodeStatus
          getDownloadLink:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              Payload.$: "$.presignedUrlInput"
              FunctionName.$: "$.configuration.getDownloadLinkFunction"
            InputPath: "$"
            ResultPath: "$.downloadLinkOutput"
            Next: sendTemplatedEmail
          sendTemplatedEmail:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              Payload:
                to.$: "$.sendEmailInput.to"
                from.$: "$.sendEmailInput.from"
                template.$: "$.sendEmailInput.template"
                params:
                  downloadLink.$: "$.downloadLinkOutput.Payload.downloadLink"
                  fileSetId.$: "$.sendEmailInput.params.fileSetId"
                  fileSetLabel.$: "$.sendEmailInput.params.fileSetLabel"
                  workId.$: "$.sendEmailInput.params.workId"
                  fileType.$: "$.sendEmailInput.params.fileType"
              FunctionName.$: "$.configuration.sendTemplatedEmailFunction"
            End: true
          failWorkflow:
            Type: Fail
      Name: !Sub "${AWS::StackName}-av-download-state-machine"
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: LambaInvokePermissions
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt startAudioTranscodeFunction.Arn
                - !GetAtt startTranscodeFunction.Arn
                - !GetAtt transcodeStatusFunction.Arn
                - !GetAtt getDownloadLinkFunction.Arn
                - !GetAtt sendTemplatedEmailFunction.Arn
  avDownloadEmailTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        TemplateName: !Sub "${AWS::StackName}-av-download-template"
        SubjectPart: Download of {{fileSetLabel}} is ready!
        TextPart: |
          Hello,
          Your request for {{fileType}} download of {{fileSetLabel}} (file set id: {{fileSetId}}) has been fulfilled. Your download will be available for 3 days.
          The {{fileType}} file can be downloaded from {{downloadLink}}
        HtmlPart: |
          <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
          <html xmlns='http://www.w3.org/1999/xhtml'>
            <head>
              <meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
              <title>NUL Meadow Download</title>
              <meta content='IE=edge' http-equiv='X-UA-Compatible' />
              <style>
                p {
                  margin-top: 0;
                  line-height: 1.4em;
                }
                a {
                  color: #4e2a84;
                }
                @media only screen and (max-width: 599px) {
                  table[class='body-table'] {
                    width: 100%;
                  }
                  img {
                    max-width: 100%;
                    height: auto !important;
                  }
                }
                @media only screen and (max-width: 510px) {
                  table[class='inside-table'] {
                    width: 100%;
                    padding: 0 10px 0 10px !important;
                  }
                  table[class='quote-table'] {
                    width: 100%;
                  }
                  table[class='quote-image-table'] {
                    width: 100%;
                  }
                }
              </style>
            </head>

            <body
              style='
                background-color: #f1f0f0;
                padding: 0;
                margin: 0;
                font-family: Arial, Helvetica Neue, Helvetica, sans-serif;
                font-size: 17px;
                color: #342f2e;
              '
            >
              <!--[if gte mso 15]><table border='0' cellpadding='0' cellspacing='0' width='100%' align='left'><tr><td><![endif]-->
              <table
                align='center'
                border='0'
                cellpadding='0'
                cellspacing='0'
                class='body-table'
                style='border: 1px solid #d8d6d6; background-color: #ffffff'
                width='600'
              >
                <!-- header -->
                <tbody>
                  <tr>
                    <td>
                      <table
                        border='0'
                        cellpadding='0'
                        cellspacing='0'
                        style='margin-bottom: 40px'
                        width='100%'
                      >
                        <tbody>
                          <tr>
                            <td
                              align='center'
                              height='110'
                              style='background-color: #4e2a84; padding: 0 10px 0 10px'
                              valign='middle'
                            >
                              <h1>
                                <img src="https://nul-public.s3.amazonaws.com/work-archiver/northwestern_logo.png" alt="Northwestern University Logo" />
                              </h1>
                            </td>
                          </tr>
                          <tr>
                            <td
                              align='center'
                              height='40'
                              style='
                                background-color: #401f68;
                                font-size: 13px;
                                color: #ffffff;
                                font-style: italic;
                              '
                              valign='middle'
                            ></td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <table
                        align='center'
                        border='0'
                        cellpadding='0'
                        cellspacing='0'
                        class='inside-table'
                        style='margin-bottom: 40px; padding: 0 66px 0 66px'
                        width='100%'
                      >
                        <tbody>
                          <tr>
                            <td style='padding-bottom: 5px'>
                              <h2
                                style='
                                  margin: 12px 0;
                                  font-size: 32px;
                                  line-height: 1.2em;
                                '
                              >
                                Hello,
                              </h2>
                              <p>
                                Your request for {{fileType}} download of <b>{{fileSetLabel}}</b> (file set id: {{fileSetId}}) has been
                                fulfilled. Click below to download your file:
                              </p>
                              <p style='text-align: center'>
                                <a href='{{downloadLink}}'>
                                  <!-- icon licensed under Creative Commons (Attribution 3.0 Unported): https://www.iconfinder.com/icons/285629/zip_file_icon -->
                                  <img src="https://iiif.dc.library.northwestern.edu/iiif/2/00000000-0000-0000-0000-000000000002/square/100,100/0/default.jpg" alt="{{downloadLink}}" />
                                </a>
                              </p>
                              <p style='text-align: center; font-style: italic'>
                                (Your <a href='{{downloadLink}}'>download</a> will be available for 3 days)
                              </p>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                  <!-- footer -->
                  <tr>
                    <td>
                      <table
                        align='center'
                        border='0'
                        cellpadding='0'
                        cellspacing='0'
                        style='background-color: #4e2a84; padding: 20px 0 20px 0'
                        width='100%'
                      >
                        <tbody>
                          <tr>
                            <td align='center' style='padding-bottom: 10px'>
                              <p>
                                <a href='https://www.library.northwestern.edu'
                                  ><img
                                    alt='Northwestern University Library'
                                    src='https://nul-public.s3.amazonaws.com/work-archiver/northwestern-university.png'
                                /></a>
                              </p>
                            </td>
                          </tr>
                          <tr>
                            <td align='center' style='padding-bottom: 20px'>
                              <p style='font-size: 12px; font-weight: bold; margin: 0'>
                                <a
                                  href='https://meadow.library.northwestern.edu'
                                  style='color: #ffffff'
                                  >VISIT MEADOW NOW</a
                                >
                              </p>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                </tbody>
              </table>
              <!--[if gte mso 15]></td></tr></table><![endif]-->
            </body>
          </html>
  ffmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: "FFMPEG Lambda Layer"
      ContentUri: ./layers/ffmpeg
      CompatibleRuntimes:
        - nodejs18.x
  startAudioTranscodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      CodeUri: ./lambdas
      Handler: start-audio-transcode.handler
      Description: Performs audio transcode job with ffmpeg
      Timeout: 900
      MemorySize: 10240
      Layers:
        - !Ref ffmpegLayer
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: BucketAccess
              Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::${MediaConvertDestinationBucket}/*"
      Environment:
        Variables:
          MEDIA_CONVERT_DESTINATION_BUCKET: !Ref MediaConvertDestinationBucket
  startTranscodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      CodeUri: ./lambdas
      Handler: start-transcode.handler
      Description: Creates MediaConvert Job to transcode HLS stream
      Environment:
        Variables:
          MEDIA_CONVERT_ENDPOINT: !Ref MediaConvertEndpoint
          MEDIA_CONVERT_JOB_QUEUE_ARN: !Ref MediaConvertJobQueueArn
          MEDIA_CONVERT_ROLE_ARN: !Ref MediaConvertRoleArn
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: PassMediaConvertRole
              Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - !Ref MediaConvertRoleArn
            - Sid: StartTranscodeJob
              Effect: Allow
              Action:
                - mediaconvert:CreateJob
              Resource: "*"
  transcodeStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      CodeUri: ./lambdas
      Handler: transcode-status.handler
      Description: Determines when transcode job has completed or errored
      Environment:
        Variables:
          MEDIA_CONVERT_ENDPOINT: !Ref MediaConvertEndpoint
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: TranscodeJobStatus
              Effect: Allow
              Action:
                - mediaconvert:GetJob
                - mediaconvert:ListJobs
              Resource: "*"
  getDownloadLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      CodeUri: ./lambdas
      Handler: get-download-link.handler
      Description: Creates presigned url
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: BucketAccess
              Effect: Allow
              Action:
                - s3:PutObjectAcl
              Resource: !Sub "arn:aws:s3:::${MediaConvertDestinationBucket}/*"
  sendTemplatedEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      CodeUri: ./lambdas
      Handler: send-templated-email.handler
      Description: Sends email
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: SESSendEmail
              Effect: Allow
              Action:
                - ses:SendTemplatedEmail
              Resource: "*"
