/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Initiate a user login */
    get: operations["getAuthLogin"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Obtain a bearer auth token for the logged in user */
    get: operations["getAuthToken"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/whoami": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Obtain information about the logged in user */
    get: operations["getAuthWhoami"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/collections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCollections"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/collections/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCollectionById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/collections/{id}/thumbnail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getCollectionThumbnail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/file-sets/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getFileSetById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/file-sets/{id}/annotations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getFileSetAnnotations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/annotations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAnnotationById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/file-sets/{id}/authorization": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getFileSetAuth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/file-sets/{id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getFileSetDownload"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/works/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getWorkById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/works/{id}/similar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSimilarWorks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/works/{id}/thumbnail": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getWorkThumbnail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSearch"];
    put?: never;
    post: operations["postSearch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search/{models}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSearchWithModels"];
    put?: never;
    post: operations["postSearchWithModels"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oai": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["oaiGet"];
    put?: never;
    post: operations["oaiPost"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CollectionRepresentativeImage: {
      /** Format: uuid */
      work_id: string | null;
      /** Format: uri */
      url: string;
    } | null;
    /**
     * @description The access level of the resource
     * @enum {string|null}
     */
    Visibility: "Private" | "Institution" | "Public" | null;
    Collection: {
      admin_email: string | null;
      api_link: string;
      api_model: string;
      /** Format: date-time */
      create_date: string;
      description: string | null;
      featured: boolean;
      /** Format: uri */
      finding_aid_url: string | null;
      /** Format: uuuid */
      id: string;
      /** Format: uri */
      iiif_collection: string | null;
      /** Format: date-time */
      indexed_at: string | null;
      keywords: string[];
      /** Format: date-time */
      modified_date: string;
      published: boolean;
      representative_image: components["schemas"]["CollectionRepresentativeImage"];
      /** Format: uri */
      thumbnail: string;
      title: string;
      visibility: components["schemas"]["Visibility"];
    };
    /**
     * @description Role of the file set
     * @enum {string|null}
     */
    FileSetRole:
      | "Access"
      | "Auxiliary"
      | "Preservation"
      | "Supplemental"
      | null;
    FileSetBase: {
      /** Format: uuid */
      id: string;
      accession_number: string;
      description: string | null;
      download_url: string | null;
      duration: number | null;
      /** Format: uuid */
      group_with: string | null;
      height: number | null;
      label: string;
      mime_type: string | null;
      original_filename: string | null;
      poster_offset: number | null;
      rank: number;
      /** Format: uri */
      representative_image_url: string | null;
      role: components["schemas"]["FileSetRole"];
      /** Format: uri */
      streaming_url: string | null;
      /** Format: uri */
      webvtt: string | null;
      width: number | null;
    };
    Annotation: {
      /** Format: uuid */
      id: string;
      type: string;
      language: string[];
      content: string;
      model: string;
    };
    FileSet: components["schemas"]["FileSetBase"] & {
      api_link: string;
      api_model: string;
      /** Format: date-time */
      create_date: string;
      digests: {
        [key: string]: string;
      } | null;
      annotations?: components["schemas"]["Annotation"][] | null;
      extracted_metadata: Record<string, never> | null;
      indexed_at: string | null;
      /** Format: date-time */
      modified_date: string;
      published: boolean;
      visibility: components["schemas"]["Visibility"];
      /** Format: uuid */
      work_id: string | null;
    };
    ControlledTermWithRole: {
      id: string;
      facet: string;
      label: string;
      label_with_role: string;
      role: string;
      variants: string[];
    };
    ControlledTerm: {
      id: string;
      facet: string;
      label: string;
      variants: string[];
    };
    /**
     * @description NUL Library Unit
     * @enum {string|null}
     */
    LibraryUnit:
      | "Special Collections"
      | "Faculty Collections"
      | "Government and Geographic Information Collection"
      | "Herskovits Library"
      | "Music Library"
      | "Transportation Library"
      | "University Archives"
      | "University Main Library"
      | null;
    GenericIdLabel: {
      id: string;
      label: string;
    } | null;
    NavPlaceEntry: {
      /** @description Identifier for the place. */
      id: string | null;
      /** @description Human-readable label for the place. */
      label: string;
      /** @description Optional summary for the place. */
      summary: string | null;
      /** @description Longitude/latitude coordinates. */
      coordinates: number[];
    };
    /** @description Geographic points for IIIF navPlace construction. */
    NavPlace: components["schemas"]["NavPlaceEntry"][];
    /**
     * @description The type of the note
     * @enum {string}
     */
    NoteType:
      | "Awards"
      | "Bibliographical/Historical Note"
      | "Creation/Production Credits"
      | "General Note"
      | "Lanugage Note"
      | "Local Note"
      | "Performers"
      | "Statement of Responsibility"
      | "Venue/Event Date";
    /**
     * @description The preservation workflow applied to the resource
     * @enum {string|null}
     */
    PreservationLevel: "Level 1" | "Level 2" | "Level 3" | null;
    /**
     * @description Type of related resource
     * @enum {string|null}
     */
    RelatedUrlLabel:
      | "Finding Aid"
      | "Hathi Trust"
      | "Related Information"
      | "Resource Guide"
      | null;
    /** @description Information about the representative image for the resource */
    RepresentativeFileSet: {
      aspect_ratio: number;
      /** Format: uuid */
      id?: string | null;
      /** Format: uri */
      url: string;
    } | null;
    /**
     * @description Preservation status of the resource
     * @enum {string|null}
     */
    Status: "Not Started" | "In Progress" | "Done" | null;
    /**
     * @description The media type of the resource
     * @enum {string|null}
     */
    WorkType: "Audio" | "Image" | "Video" | null;
    /** @description A single work response */
    Work: {
      /** @description A summary of the resource */
      abstract: string[];
      /** @description Accession number for the work. Serves as basis for the filename. */
      accession_number: string;
      alternate_title: string[];
      /** @description DC API url */
      api_link: string | null;
      /** @description Type of resource. (Work, FileSet, Collection) */
      api_model: string | null;
      /** @description Archival Resource Key (ARK) */
      ark: string;
      /** @description Associated batch update operations */
      batch_ids: string[];
      /** @description The IIIF behavior of the resource */
      behavior: string | null;
      /** @description Physical box name. Sometimes used with Distinctive Collections materials. */
      box_name: string[];
      /** @description Physical box number. Sometimes used with Distinctive Collections materials. */
      box_number: string[];
      /** @description The caption for a resource. */
      caption: string[];
      /** @description Alma bibliographic ID. */
      catalog_key: string[];
      /** @description The parent collection of the resource */
      collection: {
        /** @description UUID of the collection */
        id: string;
        /** @description Description of the collection */
        description?: string | null;
        /** @description Title of the collection */
        title: string;
      } | null;
      /** @description An entity responsible for making contributions to the resource */
      contributor: components["schemas"]["ControlledTermWithRole"][];
      /**
       * Format: date-time
       * @description The creation date of the record in the repository.
       */
      create_date: string;
      /** @description An entity primarily responsible for making the resource */
      creator: components["schemas"]["ControlledTerm"][];
      /** @description Associated csv metadata update operations */
      csv_metadata_update_jobs: string[];
      /** @description The cultural context of the resource. */
      cultural_context: string[];
      /** @description A point or a period of time associatied with an event in the lifecycle of the resource. */
      date_created: string[];
      /** @description An account of the resource. */
      description: string[];
      /** @description Vector representation of the resource's location in the repository's semantic space. */
      embedding: number[];
      /** @description The name of the inference model used to generate the `embedding` from the resource's content. */
      embedding_model: string;
      /** @description The length of the embedding text in bytes. */
      embedding_text_length: string;
      /** @description File sets associated with the resource. */
      file_sets: components["schemas"]["FileSetBase"][];
      /** @description Name of the containing folder. */
      folder_name: string[];
      /** @description Number of the containing folder. */
      folder_number: string[];
      /** @description Describes what the original object is, not what it is about. */
      genre: components["schemas"]["ControlledTerm"][];
      /**
       * Format: uuid
       * @description UUID for the work record in the repository.
       */
      id: string;
      /** @description Identifiers for the object */
      identifier: string[];
      /** Format: uri */
      iiif_manifest: string | null;
      /** Format: date-time */
      indexed_at: string | null;
      /** @description Associated ingest project */
      ingest_project: {
        /** Format: uuid */
        id: string;
        title: string;
      } | null;
      /** @description Associated ingest sheet */
      ingest_sheet: {
        /** Format: uuid */
        id: string;
        title: string;
      } | null;
      /** @description Keywords or tags used to describe this content. */
      keywords: string[];
      /** @description A language of the resource. */
      language: components["schemas"]["ControlledTerm"][];
      /** @description PIDs from previous repository. */
      legacy_identifier: string[];
      library_unit: components["schemas"]["LibraryUnit"];
      /** @description Creative Commons licenses */
      license: components["schemas"]["GenericIdLabel"];
      /** @description Place of publication. */
      location: components["schemas"]["ControlledTerm"][];
      nav_place: components["schemas"]["NavPlace"];
      /**
       * Format: date-time
       * @description Date resource last modified in repository
       */
      modified_date: string;
      notes: {
        note: string;
        type: components["schemas"]["NoteType"];
      }[];
      /** @description The material or physical carrier of the resource. */
      physical_description_material: string[];
      /** @description The size or duration of the resource. */
      physical_description_size: string[];
      preservation_level: components["schemas"]["PreservationLevel"];
      /** @description Project related information */
      project: {
        desc: string | null;
        cycle: string | null;
        manager: string | null;
        name: string | null;
        proposer: string | null;
        task_number: string | null;
      } | null;
      /** @description Location of Physical Object // will also include messy dates. Information about the provenance, such as origin, ownership and custodial history (chain of custody), of a resource. */
      provenance: string[];
      /** @description Resource is available on Digital Collections. */
      published: boolean;
      /** @description An entity responsible for making the resource available. */
      publisher: string[];
      /** @description URL of a related resource. */
      related_url: {
        /** Format: uri */
        url: string;
        label: components["schemas"]["RelatedUrlLabel"];
      }[];
      representative_file_set: components["schemas"]["RepresentativeFileSet"];
      /** @description A person or organization owning or managing rights over the resource. */
      rights_holder: string[];
      /** @description Expresses the copyright status of the resource. */
      rights_statement: components["schemas"]["GenericIdLabel"];
      /** @description Sometimes used with Distincitive Collections materials */
      scope_and_contents: string[];
      /** @description Sometimes used with Distincitive Collections materials. Used for archival series and subseries information. */
      series: string[];
      /** @description A related resource from which the described resource is derived. Source of digital object - book, journal, etc. Follow Chicago Manual of Style for citation. */
      source: string[];
      status: components["schemas"]["Status"];
      /** @description A defined style, historical period, group, school, dynasty, movement, etc. whose characteristics are represented in the work. */
      style_period: components["schemas"]["ControlledTerm"][];
      /** @description A defined style, historical period, group, school, dynasty, movement, etc. whose characteristics are represented in the work. */
      subject: components["schemas"]["ControlledTermWithRole"][];
      /** @description Used to provide the titles of separate works or parts of a resource. Information provided may also contain statements of responsibility or other sequential designations. */
      table_of_contents: string[];
      /** @description A defined style, historical period, group, school, dynasty, movement, etc. whose characteristics are represented in the work. */
      technique: components["schemas"]["ControlledTerm"][];
      /** @description Terms of use of resource. */
      terms_of_use: string | null;
      /**
       * Format: uri
       * @description Url of thumbnail image.
       */
      thumbnail: string | null;
      /** @description A name given to the resource */
      title: string | null;
      visibility: components["schemas"]["Visibility"];
      work_type: components["schemas"]["WorkType"];
    };
    /** @description A single index document */
    IndexDocument:
      | components["schemas"]["Collection"]
      | components["schemas"]["FileSet"]
      | components["schemas"]["Work"];
    /** @description Pagination info for the current response. */
    PaginationInfo: {
      /** @description Full URL to the next page of results */
      next_url?: string;
      /** @description Full URL to the previous page of results */
      prev_url?: string;
      /** @description Base URL to repeat this query for a given page */
      query_url?: string;
      /** @description Tokenized query to use in subsequent GET requests */
      search_token?: string;
      /** @description Index of current page of results */
      current_page?: number;
      /** @description Number of results per page */
      limit?: number;
      /** @description Starting index of first result on the current page */
      offset?: number;
      /** @description Total number of results */
      total_hits?: number;
      /** @description Total number of result pages */
      total_pages?: number;
    };
    /** @description Additional Information */
    Info: {
      description: string;
      /** Format: date-time */
      link_expiration?: string | null;
      name: string;
      version: string;
    };
    OpenSearchResponse: {
      /** @description An array of response documents */
      data?: components["schemas"]["IndexDocument"][];
      pagination?: components["schemas"]["PaginationInfo"];
      info?: components["schemas"]["Info"];
    };
    /** @description A [IIIF Presentation v3.x](https://iiif.io/api/presentation/3.0/) Manifest */
    IiifPresentationManifest: Record<string, never>;
  };
  responses: {
    /** @description A page of search results */
    SearchResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json":
          | components["schemas"]["OpenSearchResponse"]
          | components["schemas"]["IiifPresentationManifest"];
      };
    };
    /** @description A single document response */
    DocumentResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          data?:
            | components["schemas"]["IndexDocument"]
            | components["schemas"]["IiifPresentationManifest"];
          info?: Record<string, never>;
        };
      };
    };
    /** @description Annotations for a FileSet */
    AnnotationsResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          data?: components["schemas"]["Annotation"][] | null;
          info?: components["schemas"]["Info"];
        };
      };
    };
    /** @description A single annotation response */
    AnnotationResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          data?: components["schemas"]["Annotation"];
          info?: components["schemas"]["Info"];
        };
      };
    };
  };
  parameters: {
    /** @description Desired output format */
    as: "iiif" | "opensearch";
    /** @description Page number of results to retrieve */
    page: number;
    /** @description Maximum number of results per page */
    size: number;
    /** @description Comma-delimited list of fields to sort search results (e.g. "create_date:asc,modified_date:desc") */
    sort: string;
    /** @description Collection, FileSet, or Work ID */
    id: string;
    /** @description Desired aspect ratio */
    thumbnailAspect: "full" | "square";
    /** @description Size of largest dimension */
    thumbnailSize: number;
    /** @description Keyword query */
    query: string;
    /** @description Search token from previous search response */
    searchToken: string;
    /** @description Filter search results by visibility */
    visibility: ("public" | "institution" | "private")[];
    /** @description Comma-delimited list of models to search */
    models: ("collections" | "file-sets" | "works")[];
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getAuthLogin: {
    parameters: {
      query?: {
        /** @description Email address to use for magic link login */
        email?: string;
        /** @description URL to redirect to after login */
        goto?: string;
      };
      header?: never;
      path: {
        /** @description The authentication provider to use */
        provider: "nusso" | "magic";
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A redirect to the login page */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAuthToken: {
    parameters: {
      query?: {
        /** @description TTL in seconds for the token expiration */
        ttl?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Authentication token response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            token?: string;
            /** Format: date-time */
            expires?: string;
          };
        };
      };
    };
  };
  getAuthWhoami: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  getCollections: {
    parameters: {
      query?: {
        /** @description Desired output format */
        as?: components["parameters"]["as"];
        /** @description Page number of results to retrieve */
        page?: components["parameters"]["page"];
        /** @description Maximum number of results per page */
        size?: components["parameters"]["size"];
        /** @description Comma-delimited list of fields to sort search results (e.g. "create_date:asc,modified_date:desc") */
        sort?: components["parameters"]["sort"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["SearchResponse"];
    };
  };
  getCollectionById: {
    parameters: {
      query?: {
        /** @description Desired output format */
        as?: components["parameters"]["as"];
      };
      header?: never;
      path: {
        /** @description Collection, FileSet, or Work ID */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["DocumentResponse"];
    };
  };
  getCollectionThumbnail: {
    parameters: {
      query?: {
        /** @description Desired aspect ratio */
        aspect?: components["parameters"]["thumbnailAspect"];
        /** @description Size of largest dimension */
        size?: components["parameters"]["thumbnailSize"];
      };
      header?: never;
      path: {
        /** @description Collection, FileSet, or Work ID */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A thumbnail image for the given collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "image/jpeg": string;
        };
      };
    };
  };
  getFileSetById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Collection, FileSet, or Work ID */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["DocumentResponse"];
    };
  };
  getFileSetAnnotations: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Collection, FileSet, or Work ID */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["AnnotationsResponse"];
    };
  };
  getAnnotationById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Collection, FileSet, or Work ID */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["AnnotationResponse"];
    };
  };
  getFileSetAuth: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Collection, FileSet, or Work ID */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The resource is authorized */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The resource is not authorized */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getFileSetDownload: {
    parameters: {
      query: {
        /** @description Email to send the download link to */
        email: string;
      };
      header?: never;
      path: {
        /** @description Id of the file set */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The download is being created */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Method Not allowed for work type, file set role combo */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getWorkById: {
    parameters: {
      query?: {
        /** @description Desired output format */
        as?: components["parameters"]["as"];
      };
      header?: never;
      path: {
        /** @description Collection, FileSet, or Work ID */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["DocumentResponse"];
    };
  };
  getSimilarWorks: {
    parameters: {
      query?: {
        /** @description Page number of results to retrieve */
        page?: components["parameters"]["page"];
        /** @description Maximum number of results per page */
        size?: components["parameters"]["size"];
        /** @description Comma-delimited list of fields to sort search results (e.g. "create_date:asc,modified_date:desc") */
        sort?: components["parameters"]["sort"];
        /** @description Desired output format */
        as?: components["parameters"]["as"];
      };
      header?: never;
      path: {
        /** @description Collection, FileSet, or Work ID */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["SearchResponse"];
    };
  };
  getWorkThumbnail: {
    parameters: {
      query?: {
        /** @description Desired aspect ratio */
        aspect?: components["parameters"]["thumbnailAspect"];
        /** @description Size of largest dimension */
        size?: components["parameters"]["thumbnailSize"];
      };
      header?: never;
      path: {
        /** @description Collection, FileSet, or Work ID */
        id: components["parameters"]["id"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A thumbnail image for the given work */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "image/jpeg": string;
        };
      };
    };
  };
  getSearch: {
    parameters: {
      query?: {
        /** @description Keyword query */
        query?: components["parameters"]["query"];
        /** @description Search token from previous search response */
        searchToken?: components["parameters"]["searchToken"];
        /** @description Page number of results to retrieve */
        page?: components["parameters"]["page"];
        /** @description Maximum number of results per page */
        size?: components["parameters"]["size"];
        /** @description Comma-delimited list of fields to sort search results (e.g. "create_date:asc,modified_date:desc") */
        sort?: components["parameters"]["sort"];
        /** @description Desired output format */
        as?: components["parameters"]["as"];
        /** @description Filter search results by visibility */
        visibility?: components["parameters"]["visibility"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["SearchResponse"];
    };
  };
  postSearch: {
    parameters: {
      query?: {
        /** @description Page number of results to retrieve */
        page?: components["parameters"]["page"];
        /** @description Maximum number of results per page */
        size?: components["parameters"]["size"];
        /** @description Comma-delimited list of fields to sort search results (e.g. "create_date:asc,modified_date:desc") */
        sort?: components["parameters"]["sort"];
        /** @description Desired output format */
        as?: components["parameters"]["as"];
        /** @description Filter search results by visibility */
        visibility?: components["parameters"]["visibility"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": Record<string, any>;
      };
    };
    responses: {
      200: components["responses"]["SearchResponse"];
    };
  };
  getSearchWithModels: {
    parameters: {
      query?: {
        /** @description Keyword query */
        query?: components["parameters"]["query"];
        /** @description Search token from previous search response */
        searchToken?: components["parameters"]["searchToken"];
        /** @description Page number of results to retrieve */
        page?: components["parameters"]["page"];
        /** @description Maximum number of results per page */
        size?: components["parameters"]["size"];
        /** @description Comma-delimited list of fields to sort search results (e.g. "create_date:asc,modified_date:desc") */
        sort?: components["parameters"]["sort"];
        /** @description Desired output format */
        as?: components["parameters"]["as"];
        /** @description Filter search results by visibility */
        visibility?: components["parameters"]["visibility"];
      };
      header?: never;
      path: {
        /** @description Comma-delimited list of models to search */
        models: components["parameters"]["models"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["SearchResponse"];
    };
  };
  postSearchWithModels: {
    parameters: {
      query?: {
        /** @description Page number of results to retrieve */
        page?: components["parameters"]["page"];
        /** @description Maximum number of results per page */
        size?: components["parameters"]["size"];
        /** @description Comma-delimited list of fields to sort search results (e.g. "create_date:asc,modified_date:desc") */
        sort?: components["parameters"]["sort"];
        /** @description Desired output format */
        as?: components["parameters"]["as"];
        /** @description Filter search results by visibility */
        visibility?: components["parameters"]["visibility"];
      };
      header?: never;
      path: {
        /** @description Comma-delimited list of models to search */
        models: components["parameters"]["models"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": Record<string, any>;
      };
    };
    responses: {
      200: components["responses"]["SearchResponse"];
    };
  };
  oaiGet: {
    parameters: {
      query: {
        /** @description All OAI-PMH verbs are supported. */
        verb:
          | "GetRecord"
          | "Identify"
          | "ListIdentifiers"
          | "ListMetadataFormats"
          | "ListRecords"
          | "ListSets";
        /**
         * @description Required for `GetRecord` requests
         * @example d75a851f-b773-4bdf-baec-62a8ec974126
         */
        identifier?: string;
        /** @description Required for `ListIdentifiers`, `ListRecords`, and `GetRecord` requests */
        metadataPrefix?: "oai_dc";
        /**
         * @description Optional for `ListRecords` and `ListIdentifiers` requests, based on a record's modified date. Accepted formats `YYYY-MM-DD` or `YYYY-MM-DDThh:mm:ssZ`
         * @example 2023-01-01T08:12:23Z
         */
        from?: string;
        /**
         * @description Optional for `ListRecords` and `ListIdentifiers` requests, based on a record's modified date. Accepted formats `YYYY-MM-DD` or `YYYY-MM-DDThh:mm:ssZ`
         * @example 2023-01-12T12:03:59Z
         */
        until?: string;
        /**
         * @description Optional for `ListRecords` and `ListIdentifiers` requests, based on a collection id.
         * @example c4f30015-88b5-4291-b3a6-8ac9b7c7069c
         */
        set?: string;
        /** @description Exclusive parameter for retrieving additional results */
        resumptionToken?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description An OAI-PMH response document */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/xml": Record<string, never>;
        };
      };
    };
  };
  oaiPost: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description All OAI-PMH verbs are supported */
          verb?: string;
          /** @description Required for `GetRecord` requests */
          identifier?: string;
          /** @description Required for `ListIdentifiers`, `ListRecords`, and `GetRecord` requests. The only supported value is `"oai_dc"` currently. */
          metadataPrefix?: string;
          /** @description Exclusive parameter for retrieving additional results */
          resumptionToken?: string;
          /** @description Optional for `ListRecords` and `ListIdentifiers` requests, based on a record's modified date. Accepted formats `YYYY-MM-DD` or `YYYY-MM-DDThh:mm:ssZ` */
          from?: string;
          /** @description Optional for `ListRecords` and `ListIdentifiers` requests, based on a record's modified date. Accepted formats `YYYY-MM-DD` or `YYYY-MM-DDThh:mm:ssZ` */
          until?: string;
          /** @description Optional for `ListRecords` and `ListIdentifiers` requests, based on a collection id. */
          set?: string;
        };
      };
    };
    responses: {
      /** @description An OAI-PMH response document */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/xml": Record<string, never>;
        };
      };
    };
  };
}
