import {
  describe,
  it,
  beforeAll,
  beforeEach,
  afterEach,
  afterAll,
  expect,
} from "bun:test";
import { http, HttpResponse } from "msw";
import { setupServer } from "msw/node";
import { Reader } from "@contentauth/c2pa-node";
import convert, { type ElementCompact } from "xml-js";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  buildRequest,
  sendRequest,
  setupEnv,
  teardownEnv,
  testFixture,
} from "../test-helpers/index.ts";

const WORK_URL =
  "https://index.test.library.northwestern.edu/dc-v2-work/_doc/1234";
const IPTC = "http://cv.iptc.org/newscodes/digitalsourcetype";
const SOURCE_ID = "work:0f1e2d3c-0000-4000-8000-000000000001";
// A file set of the work fixture (mocks/work-1234.json), with a mime type.
const FILE_SET_ID = "076dcbd8-8c57-40e8-bdf7-dc9153c87a36";
const PREMIS_XSD = new URL("../fixtures/premis/premis.xsd", import.meta.url)
  .pathname;

// What Meadow.AI.Provenance.Export indexes for a work whose description was
// generated by AI and then edited by a person.
const exports = {
  premis: {
    premis_version: "3.0",
    scope: { work_id: "1234" },
    objects: [
      {
        identifier: { type: "Meadow Work", value: "1234" },
        category: "intellectual_entity",
        role: "replace",
        type: "Work",
        target_id: "1234",
        field_path: "descriptive_metadata.description",
        restricted: false,
        fixity: null,
      },
      {
        identifier: { type: "Meadow FileSet", value: FILE_SET_ID },
        category: "file",
        role: "source",
        type: "FileSet",
        work_id: "1234",
        file_set_id: FILE_SET_ID,
        access_link: "https://thisisafakedcurl/items/1234",
        restricted: false,
        fixity: {
          message_digest_algorithm: "sha256",
          message_digest: "ab".repeat(32),
        },
      },
      {
        identifier: { type: "Meadow FileSet", value: "not-a-file-set" },
        category: "file",
        role: "source",
        type: "FileSet",
        file_set_id: "not-a-file-set",
        fixity: null,
      },
    ],
    events: [
      {
        identifier: { type: "Meadow AI activity event", value: "event-1" },
        type: "metadata generation",
        date_time: "2026-09-01T12:00:00.000000Z",
        outcome: "success",
        outcome_detail: null,
        activity_id: "activity-1",
        target: { type: "Meadow Work", value: "1234" },
        linking_agents: [],
      },
      {
        identifier: { type: "Meadow AI activity event", value: "event-2" },
        type: "metadata modification",
        date_time: "2026-09-02T12:00:00.000000Z",
        outcome: "success",
        outcome_detail: "Edited & approved",
        activity_id: "activity-1",
        target: { type: "Meadow Work", value: "1234" },
        linking_agents: [
          {
            role: "reviewer",
            agent_identifier: { type: "role", value: "staff" },
          },
        ],
      },
    ],
    agents: [
      {
        identifier: { type: "model", value: "test-model" },
        type: "model",
        name: "test-model",
        version: "v1",
      },
      {
        identifier: { type: "role", value: "staff" },
        type: "human",
        name: "Northwestern University Libraries staff",
        version: null,
      },
    ],
    rights: [
      {
        basis: "policy",
        policy: "retain_internal",
        activity_id: "activity-1",
        note: "AI provenance retention policy recorded by Meadow",
      },
    ],
  },
  c2pa: {
    standard: "C2PA",
    spec_version: "2.4",
    scope: { work_id: "1234" },
    digital_source_type: `${IPTC}/compositeWithTrainedAlgorithmicMedia`,
    actions: [
      {
        action: "c2pa.edited",
        when: "2026-09-01T12:00:00.000000Z",
        softwareAgent: { name: "test-model", version: "v1" },
        digitalSourceType: `${IPTC}/trainedAlgorithmicMedia`,
        description:
          "AI-generated value applied to descriptive_metadata.description",
        parameters: {
          ingredientIds: [SOURCE_ID, "work:not-an-ingredient"],
          "edu.northwestern.library.fieldPath":
            "descriptive_metadata.description",
        },
      },
      {
        action: "c2pa.edited",
        when: "2026-09-02T12:00:00.000000Z",
        softwareAgent: { name: "Meadow" },
        digitalSourceType: `${IPTC}/humanEdits`,
        description:
          "AI-generated value of descriptive_metadata.description edited by a human",
        parameters: {
          "edu.northwestern.library.fieldPath":
            "descriptive_metadata.description",
        },
      },
    ],
    ai_disclosures: [
      {
        modelType: "c2pa.types.model",
        modelName: "test-model",
        contentProfile: { humanOversightLevel: "human_validated" },
      },
    ],
    ingredients: [
      {
        id: SOURCE_ID,
        "dc:title": "Work Voyager:2569718",
        relationship: "inputTo",
        instanceID: "urn:uuid:0f1e2d3c-0000-4000-8000-000000000001",
        informationalURI: "https://thisisafakedcurl/items/source",
        description: "Source material provided to the AI model",
      },
    ],
  },
};

function workFixture(withProvenance: boolean): Record<string, unknown> {
  const doc = JSON.parse(testFixture("mocks/work-1234.json"));
  if (withProvenance) {
    doc._source.ai_provenance_exports = exports;
    // As indexed before Meadow stopped naming the reviewer.
    doc._source.ai_provenance = {
      descriptive_metadata: {
        description: {
          origin: "ai_assisted_human_modified",
          model: "test-model",
          reviewer: "staff-netid",
        },
      },
    };
  }
  return doc;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ManifestStoreJson = Record<string, any>;

const signingEnv = {
  C2PA_CERTIFICATE: testFixture("c2pa/test-chain.pem"),
  // Flattened newlines, as the key would arrive from an env file.
  C2PA_KEY: testFixture("c2pa/test-key.pem").replace(/\n/g, "\\n"),
};

async function get(
  as?: string,
  headers: Record<string, string> = {},
): Promise<Response> {
  return await sendRequest(
    buildRequest("GET", "/works/{id}", {
      pathParams: { id: 1234 },
      queryParams: as ? { as } : {},
      headers,
    }),
  );
}

const asJson = { accept: "application/json" };

/**
 * Validates a document against the PREMIS 3.0 schema with xmllint. Bun has no
 * schema validator of its own, so a missing xmllint fails the test rather
 * than skipping it.
 */
function validatePremis(xml: string): { valid: boolean; report: string } {
  const file = join(mkdtempSync(join(tmpdir(), "premis-")), "work.xml");
  writeFileSync(file, xml);
  const result = Bun.spawnSync([
    "xmllint",
    "--noout",
    "--nonet",
    "--schema",
    PREMIS_XSD,
    file,
  ]);
  return {
    valid: result.exitCode === 0,
    report: result.stderr.toString(),
  };
}

// The xml-js compact form of the document's `premis:premis` element, with
// repeated elements always as arrays.
function parsePremis(xml: string): ElementCompact {
  const doc = convert.xml2js(xml, {
    compact: true,
    alwaysArray: [
      "premis:object",
      "premis:event",
      "premis:agent",
      "premis:rights",
      "premis:linkingEventIdentifier",
      "premis:linkingAgentIdentifier",
      "premis:otherRightsNote",
    ],
  }) as ElementCompact;
  return doc["premis:premis"];
}

describe("Work provenance formats", () => {
  const server = setupServer();
  const serveWork = (withProvenance = true) =>
    server.use(
      http.get(WORK_URL, () => HttpResponse.json(workFixture(withProvenance))),
    );

  beforeAll(() => server.listen({ onUnhandledRequest: "error" }));
  beforeEach(() => setupEnv());
  afterEach(() => {
    server.resetHandlers();
    teardownEnv();
  });
  afterAll(() => server.close());

  describe("GET /works/{id}?as=premis", () => {
    it("returns PREMIS 3.0 XML that validates against the schema", async () => {
      serveWork();
      const result = await get("premis");
      expect(result.status).toEqual(200);
      expect(result.headers.get("content-type") ?? "").toMatch(
        /application\/xml/,
      );

      const xml = await result.text();
      const { valid, report } = validatePremis(xml);
      expect(report).toMatch(/validates|fails to validate/);
      expect(valid, report).toBe(true);

      const premis = parsePremis(xml);
      expect(premis._attributes.version).toEqual("3.0");
      expect(premis._attributes["xmlns:premis"]).toEqual(
        "http://www.loc.gov/premis/v3",
      );

      const [work, fileSet, unknownFile] = premis["premis:object"];
      expect(work._attributes["xsi:type"]).toEqual("premis:intellectualEntity");
      expect(
        work["premis:objectIdentifier"]["premis:objectIdentifierValue"]._text,
      ).toEqual("1234");
      // Events that touched the work link back to it.
      expect(
        work["premis:linkingEventIdentifier"].map(
          (link: ElementCompact) =>
            link["premis:linkingEventIdentifierValue"]._text,
        ),
      ).toEqual(["event-1", "event-2"]);
      expect(work["premis:objectCharacteristics"]).toBeUndefined();

      // A file needs a format, which comes from the work's file sets.
      expect(fileSet._attributes["xsi:type"]).toEqual("premis:file");
      expect(fileSet["premis:objectIdentifier"]._attributes.simpleLink).toEqual(
        "https://thisisafakedcurl/items/1234",
      );
      const characteristics = fileSet["premis:objectCharacteristics"];
      expect(
        characteristics["premis:fixity"]["premis:messageDigestAlgorithm"]._text,
      ).toEqual("sha256");
      expect(
        characteristics["premis:format"]["premis:formatDesignation"][
          "premis:formatName"
        ]._text,
      ).toEqual("image/tiff");
      expect(
        unknownFile["premis:objectCharacteristics"]["premis:format"][
          "premis:formatDesignation"
        ]["premis:formatName"]._text,
      ).toEqual("application/octet-stream");

      const [generated, modified] = premis["premis:event"];
      // Meadow's own term carries no authority; the LoC term does.
      expect(generated["premis:eventType"]._text).toEqual(
        "metadata generation",
      );
      expect(generated["premis:eventType"]._attributes).toBeUndefined();
      expect(modified["premis:eventType"]._attributes).toEqual({
        authority: "eventType",
        authorityURI: "http://id.loc.gov/vocabulary/preservation/eventType",
      });
      expect(
        modified["premis:eventOutcomeInformation"]["premis:eventOutcomeDetail"][
          "premis:eventOutcomeDetailNote"
        ]._text,
      ).toEqual("Edited & approved");
      const [reviewer] = modified["premis:linkingAgentIdentifier"];
      expect(reviewer["premis:linkingAgentIdentifierValue"]._text).toEqual(
        "staff",
      );
      expect(reviewer["premis:linkingAgentRole"]._text).toEqual("reviewer");
      expect(
        modified["premis:linkingObjectIdentifier"][
          "premis:linkingObjectIdentifierValue"
        ]._text,
      ).toEqual("1234");

      const [model, staff] = premis["premis:agent"];
      expect(model["premis:agentType"]._text).toEqual("model");
      expect(model["premis:agentVersion"]._text).toEqual("v1");
      expect(staff["premis:agentType"]._text).toEqual("person");
      expect(staff["premis:agentName"]._text).toEqual(
        "Northwestern University Libraries staff",
      );

      const [statement] = premis["premis:rights"].map(
        (rights: ElementCompact) => rights["premis:rightsStatement"],
      );
      expect(statement["premis:rightsBasis"]._text).toEqual("other");
      expect(
        statement["premis:otherRightsInformation"]["premis:otherRightsBasis"]
          ._text,
      ).toEqual("policy");
      expect(
        statement["premis:otherRightsInformation"][
          "premis:otherRightsNote"
        ].map((note: ElementCompact) => note._text),
      ).toEqual([
        "retain_internal",
        "AI provenance retention policy recorded by Meadow",
      ]);
    });

    it("describes a work with no AI provenance as an object with no events", async () => {
      serveWork(false);
      const result = await get("premis");
      expect(result.status).toEqual(200);

      const xml = await result.text();
      const { valid, report } = validatePremis(xml);
      expect(valid, report).toBe(true);

      const premis = parsePremis(xml);
      expect(premis["premis:object"]).toHaveLength(1);
      expect(
        premis["premis:object"][0]["premis:objectIdentifier"]._attributes
          .simpleLink,
      ).toEqual(
        "https://dcapi.rdc-staging.library.northwestern.edu/api/v2/works/1234",
      );
      expect(premis["premis:event"]).toBeUndefined();
    });

    it("returns the PREMIS projection as indexed when asked for JSON", async () => {
      serveWork();
      const result = await get("premis", asJson);
      expect(result.status).toEqual(200);
      expect(result.headers.get("content-type") ?? "").toMatch(
        /application\/json/,
      );

      const body = await result.json();
      expect(body.data).toEqual(exports.premis);
      expect(body.info.name).toEqual("dc-api");
    });

    it("returns an empty JSON projection for a work with no AI provenance", async () => {
      serveWork(false);
      const result = await get("premis", asJson);
      expect(result.status).toEqual(200);

      const { data } = await result.json();
      expect(data).toEqual({
        premis_version: "3.0",
        scope: { work_id: "1234" },
        objects: [],
        events: [],
        agents: [],
        rights: [],
      });
    });

    it("404s a missing work", async () => {
      server.use(
        http.get(WORK_URL, () =>
          HttpResponse.json(
            JSON.parse(testFixture("mocks/missing-work-1234.json")),
          ),
        ),
      );
      expect((await get("premis")).status).toEqual(404);
    });
  });

  describe("GET /works/{id}?as=c2pa without signing credentials", () => {
    it("returns the unsigned manifest definition as JSON", async () => {
      serveWork();
      const result = await get("c2pa");
      expect(result.status).toEqual(200);
      expect(result.headers.get("content-type") ?? "").toMatch(
        /application\/json/,
      );

      const { data, info } = await result.json();
      expect(info.c2pa.signed).toBe(false);
      expect(data.title).toEqual("Canary Record TEST 1");

      const [actions, disclosure, assetRef] = data.assertions;
      expect(actions.label).toEqual("c2pa.actions.v2");
      expect(actions.data.allActionsIncluded).toBe(false);
      expect(
        actions.data.actions.map((a: { action: string }) => a.action),
      ).toEqual(["c2pa.created", "c2pa.edited", "c2pa.edited"]);
      expect(actions.data.actions[0].digitalSourceType).toEqual(
        `${IPTC}/compositeWithTrainedAlgorithmicMedia`,
      );
      // Only ingredients the manifest actually carries can be referenced.
      expect(actions.data.actions[1].parameters.ingredientIds).toEqual([
        SOURCE_ID,
      ]);
      expect(disclosure.label).toEqual("c2pa.ai-disclosure");
      expect(assetRef.data.references[0].reference.uri).toMatch(
        /\/works\/1234$/,
      );
      expect(data.ingredients).toEqual([
        {
          label: SOURCE_ID,
          title: "Work Voyager:2569718",
          relationship: "inputTo",
          instance_id: "urn:uuid:0f1e2d3c-0000-4000-8000-000000000001",
          informational_URI: "https://thisisafakedcurl/items/source",
          description: "Source material provided to the AI model",
        },
      ]);
    });

    it("makes no AI claim for a work with no AI provenance", async () => {
      serveWork(false);
      const { data } = await (await get("c2pa")).json();
      const [actions, assetRef] = data.assertions;
      expect(actions.data.actions).toHaveLength(1);
      expect(actions.data.actions[0].digitalSourceType).toEqual(
        `${IPTC}/dataDrivenMedia`,
      );
      expect(assetRef.label).toEqual("c2pa.asset-ref");
      expect(data.ingredients).toEqual([]);
    });

    it("does not advertise a manifest on the default response", async () => {
      serveWork();
      const result = await get();
      expect(result.status).toEqual(200);
      expect(result.headers.get("link")).toBeNull();
    });

    it("never names the staff member who reviewed a field", async () => {
      serveWork();
      for (const as of [undefined, "premis", "c2pa"]) {
        const body = await (await get(as)).text();
        expect(body).not.toContain("staff-netid");
      }

      const { data } = await (await get()).json();
      expect(data.ai_provenance.descriptive_metadata.description).toEqual({
        origin: "ai_assisted_human_modified",
        model: "test-model",
        reviewer: "Northwestern University Libraries staff",
      });
    });

    it("404s a missing work", async () => {
      server.use(
        http.get(WORK_URL, () =>
          HttpResponse.json(
            JSON.parse(testFixture("mocks/missing-work-1234.json")),
          ),
        ),
      );
      expect((await get("c2pa")).status).toEqual(404);
    });
  });

  describe("GET /works/{id}?as=c2pa with signing credentials", () => {
    beforeEach(() => setupEnv(signingEnv));

    async function read(asset: Buffer, manifest: Buffer) {
      const reader = await Reader.fromManifestDataAndAsset(manifest, {
        buffer: asset,
        mimeType: "application/json",
      });
      const store = reader.json() as unknown as ManifestStoreJson;
      return {
        store,
        manifest: store.manifests[store.active_manifest],
        failures: (store.validation_results?.activeManifest?.failure ?? []).map(
          (status: { code: string }) => status.code,
        ),
      };
    }

    it("advertises the manifest on the default response", async () => {
      serveWork();
      const result = await get();
      expect(result.headers.get("link")).toEqual(
        '<https://dcapi.rdc-staging.library.northwestern.edu/api/v2/works/1234?as=c2pa>; rel="c2pa-manifest"',
      );
      expect(result.headers.get("access-control-expose-headers")).toMatch(
        /Link/,
      );
    });

    it("serves a default response with no per-request content", async () => {
      // The manifest is bound to these bytes, so two fetches of the record
      // must agree, and `info` may carry nothing that varies by request.
      serveWork();
      const first = await (await get()).text();
      const second = await (await get()).text();
      expect(second).toEqual(first);

      const { info } = JSON.parse(first);
      expect(Object.keys(info).sort()).toEqual([
        "description",
        "link_expiration",
        "name",
        "version",
      ]);
      expect(info.link_expiration).toBeNull();
    });

    it("signs a manifest bound to the default response body", async () => {
      serveWork();
      const asset = Buffer.from(await (await get()).arrayBuffer());

      const result = await get("c2pa");
      expect(result.status).toEqual(200);
      expect(result.headers.get("content-type")).toEqual("application/c2pa");
      expect(result.headers.get("content-disposition")).toEqual(
        'attachment; filename="1234.c2pa"',
      );
      const signed = Buffer.from(await result.arrayBuffer());

      const { store, manifest, failures } = await read(asset, signed);
      // The test certificate chains to nothing; everything else must hold.
      expect(failures).toEqual(["signingCredential.untrusted"]);
      expect(store.validation_state).toEqual("Valid");
      expect(manifest.title).toEqual("Canary Record TEST 1");
      expect(manifest.claim_generator_info[0].name).toEqual("dc-api");

      const labels = manifest.assertions.map((a: { label: string }) => a.label);
      expect(labels).toEqual([
        "c2pa.actions.v2",
        "c2pa.ai-disclosure",
        "c2pa.asset-ref",
      ]);

      const [created, generated, edited] = manifest.assertions[0].data.actions;
      expect(created.action).toEqual("c2pa.created");
      expect(created.digitalSourceType).toEqual(
        `${IPTC}/compositeWithTrainedAlgorithmicMedia`,
      );
      expect(generated.digitalSourceType).toEqual(
        `${IPTC}/trainedAlgorithmicMedia`,
      );
      // c2pa-rs replaced the ingredient id with a hashed reference.
      expect(generated.parameters.ingredients).toHaveLength(1);
      expect(generated.parameters.ingredientIds).toBeUndefined();
      expect(edited.digitalSourceType).toEqual(`${IPTC}/humanEdits`);

      expect(manifest.ingredients).toHaveLength(1);
      expect(manifest.ingredients[0].relationship).toEqual("inputTo");
    });

    it("produces a manifest that does not validate against other content", async () => {
      serveWork();
      const signed = Buffer.from(await (await get("c2pa")).arrayBuffer());

      const { failures } = await read(Buffer.from('{"data":{}}'), signed);
      expect(failures).toContain("assertion.dataHash.mismatch");
    });

    it("fails rather than falling back when signing itself fails", async () => {
      setupEnv({ ...signingEnv, C2PA_KEY: "not a private key" });
      serveWork();
      const result = await get("c2pa");
      expect(result.status).toEqual(503);
      expect(result.headers.get("content-type") ?? "").not.toMatch(/c2pa/);
    });

    it("signs a manifest for a work with no AI provenance", async () => {
      serveWork(false);
      const asset = Buffer.from(await (await get()).arrayBuffer());
      const signed = Buffer.from(await (await get("c2pa")).arrayBuffer());

      const { manifest, failures } = await read(asset, signed);
      expect(failures).toEqual(["signingCredential.untrusted"]);
      expect(
        manifest.assertions.map((a: { label: string }) => a.label),
      ).toEqual(["c2pa.actions.v2", "c2pa.asset-ref"]);
      expect(manifest.ingredients ?? []).toEqual([]);
    });
  });
});
