name: Run Tests
on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "package.json"
      - "package-lock.json"
      - "src/**"
      - "test/**"
      - "template.yaml"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ci
      AWS_SECRET_ACCESS_KEY: ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - name: Check code style
        run: npm run lint && npm run prettier
      - name: Run tests
        run: npm run test:coverage
      - name: Validate OpenAPI spec
        run: npm run validate-spec
  validate-template:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: test
    steps:
      - uses: aws-actions/setup-sam@v1
      - name: sam fix https://github.com/aws/aws-sam-cli/issues/4527
        run: $(dirname $(readlink $(which sam)))/pip install --force-reinstall "cryptography==38.0.4"
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AwsAccount }}:role/github-actions-role
          aws-region: us-east-1
      - uses: actions/checkout@v3
      - name: Validate template
        run: sam build && sam validate
