name: Run NodeJS Tests
on:
  push:
    paths:
      - ".github/workflows/test-node.yml"
      - "api/**"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./api
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ci
      AWS_SECRET_ACCESS_KEY: ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: 'api/package-lock.json'
      - run: npm ci
      - name: Check code style
        run: npm run lint && npm run prettier
      - name: Run tests
        run: npm run test:coverage
      - name: Validate OpenAPI spec
        run: npm run validate-spec
