name: Run Python Tests
on:
  push:
    paths:
      - ".github/workflows/test-python.yml"
      - "chat/**"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./chat
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ci
      AWS_SECRET_ACCESS_KEY: ci
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
      - run: uv sync --group dev
      - name: Check code style
        run: uv run ruff check .
      - name: Run tests
        run: |
          uv run coverage run --include='src/**/*' -m pytest -m ""
          uv run coverage report
        env:
          AWS_REGION: us-east-1
